# Generated by Django 2.2.6 on 2019-11-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Short bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook_account',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='google_account',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Twitter account'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name="User's name"),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_url',
            field=models.URLField(blank=True, max_length=555, null=True, verbose_name='Personal URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profile picture'),
        ),
        migrations.AddField(
            model_name='user',
            name='short_bio',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Describe yourself'),
        ),
    ]
